blogs/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views


app_name = 'blogs'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
]

blogs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    '''Represents the Post table in the database'''
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField() # adding aditional field

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post


def home(request):
    '''Handles the traffic of the home page'''
    posts = Post.objects.all()

    context = {'posts': posts}
    return render(request, 'blogs/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blogs/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4


class UserPostListView(ListView):
    model = Post
    template_name = 'blogs/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


def about(request):
    context = {'title': 'About'}
    return render(request, 'blogs/about.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


class RegisterView(View):
    template_name = 'users/register.html'

    def get(self, request: HttpRequest):
        form = UserRegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request: HttpRequest):
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            #username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You\'re ready to log in!')
            return redirect(to='users:login')

        messages.warning(request, 'Form is not valid')
        return render(request, self.template_name, {'form': form})


@login_required
def profile(request: HttpRequest):
    if request.method == 'POST' and request.user.is_authenticated:
        user_form = UserUpdateForm(data=request.POST, instance=request.user)

        profile_form = ProfileUpdateForm(
            data=request.POST,
            files=request.FILES,
            instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile Updated')
            return redirect(to='users:profile')
    elif request.method == 'GET':
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'users/profile.html', context)

blogs/templates/blogs/about.html
{% extends 'blogs/base.html' %}


{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blogs/templates/blogs/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blogs/main.css' %}" />
    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'blogs:home' %}">Django Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blogs:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'blogs:about' %}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'blogs:post-create' %}">New Post</a>
                            <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages%}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>
                        You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

blogs/templates/blogs/home.html
{% extends 'blogs/base.html' %}


{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blogs:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

blogs/templates/blogs/post_confirm_delete.html
{% extends "blogs/base.html" %}


{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure  you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Yes, Delete" class="btn btn-outline-danger">
                <a class="btn btn-outline-secondary" href="{% url 'blogs:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'blogs/base.html' %}


{% block content %}
    <article class="media content-section">
        <img src="{{ object.author.profile.image.url }}" class="rounded-circle article-img" alt="">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'blogs:user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d Y" }}</small>
                {% if object.author == user %}
                   <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blogs:post-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blogs:post-delete' object.id %}">Delete</a>
                   </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
{% endblock content %}

blogs/templates/blogs/post_form.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Post" class="btn btn-outline-info">
            </div>
        </form>
    </div>
{% endblock content %}

blogs/templates/blogs/user_posts.html
{% extends 'blogs/base.html' %}


{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'blogs:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blogs:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>  
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Log In" class="btn btn-outline-info">
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account?
                <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blogs/base.html" %}


{% block content %}
    <h2>You've been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blogs/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    <form method="POST", enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
      </fieldset>
      <div class="form-group">
        <input type="submit" value="Update" class="btn btn-outline-info">
      </div>
    </form>
  </div>
{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Sign Up" class="btn btn-outline-info">
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account?
                <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}